"""PostgreSQL persistence boundary."""

from multi_agent_v2.packages.persistence.agent_models import (
    AgentExecutionAttempt,
    AgentExecutionLease,
    ProviderSession,
    WorkspaceWorktree,
)
from multi_agent_v2.packages.persistence.control_models import (
    ApprovalProjection,
    AuditLog,
    CommandOutbox,
    ConnectorCheckpoint,
    EventInbox,
    EventWaitSubscription,
    ExecutionAttemptProjection,
    IdempotencyRecord,
    ProviderCatalogSnapshot,
    ScheduleDefinition,
    TriggerDefinition,
    TriggerDelivery,
    WorkflowEvent,
    WorkflowInstanceProjection,
    WorkflowNodeProjection,
    WorkflowTemplate,
    WorkflowTemplateVersion,
)
from multi_agent_v2.packages.persistence.control_repository import (
    ConnectorAdvance,
    ConnectorCheckpointState,
    ControlPlaneConflict,
    ControlPlaneNotFound,
    ControlPlaneRepository,
    ControlPlaneRepositoryError,
    IdempotencyConflict,
    OutboxFailure,
    OutboxLeaseLost,
    RevisionConflict,
)
from multi_agent_v2.packages.persistence.database import DatabaseManager, DatabaseProbe
from multi_agent_v2.packages.persistence.execution_lease import (
    ExecutionAttemptRegistration,
    ExecutionIdentityConflict,
    ExecutionLeaseError,
    ExecutionLeaseLost,
    ExecutionLeaseRepository,
    ExecutionRegistration,
    ExecutionStateConflict,
    LeaseClaimDisposition,
    LeaseClaimResult,
    ProviderSessionBusy,
    ProviderSessionClaim,
)
from multi_agent_v2.packages.persistence.schema import (
    CURRENT_SCHEMA_REVISION,
    DatabaseSchemaError,
)
from multi_agent_v2.packages.persistence.worktree_repository import (
    CleanupClaimDisposition,
    WorktreeCleanupClaim,
    WorktreeRegistration,
    WorktreeRepository,
    WorktreeStateError,
)

__all__ = [
    "CURRENT_SCHEMA_REVISION",
    "AgentExecutionAttempt",
    "AgentExecutionLease",
    "ApprovalProjection",
    "AuditLog",
    "CleanupClaimDisposition",
    "CommandOutbox",
    "ConnectorAdvance",
    "ConnectorCheckpoint",
    "ConnectorCheckpointState",
    "ControlPlaneConflict",
    "ControlPlaneNotFound",
    "ControlPlaneRepository",
    "ControlPlaneRepositoryError",
    "DatabaseManager",
    "DatabaseProbe",
    "DatabaseSchemaError",
    "EventInbox",
    "EventWaitSubscription",
    "ExecutionAttemptProjection",
    "ExecutionAttemptRegistration",
    "ExecutionIdentityConflict",
    "ExecutionLeaseError",
    "ExecutionLeaseLost",
    "ExecutionLeaseRepository",
    "ExecutionRegistration",
    "ExecutionStateConflict",
    "IdempotencyConflict",
    "IdempotencyRecord",
    "LeaseClaimDisposition",
    "LeaseClaimResult",
    "OutboxFailure",
    "OutboxLeaseLost",
    "ProviderCatalogSnapshot",
    "ProviderSession",
    "ProviderSessionBusy",
    "ProviderSessionClaim",
    "RevisionConflict",
    "ScheduleDefinition",
    "TriggerDefinition",
    "TriggerDelivery",
    "WorkflowEvent",
    "WorkflowInstanceProjection",
    "WorkflowNodeProjection",
    "WorkflowTemplate",
    "WorkflowTemplateVersion",
    "WorkspaceWorktree",
    "WorktreeCleanupClaim",
    "WorktreeRegistration",
    "WorktreeRepository",
    "WorktreeStateError",
]
